// Code generated by capnpc-go. DO NOT EDIT.

package cryptobank

import (
	context "golang.org/x/net/context"
	capnp "zombiezen.com/go/capnproto2"
	text "zombiezen.com/go/capnproto2/encoding/text"
	schemas "zombiezen.com/go/capnproto2/schemas"
	server "zombiezen.com/go/capnproto2/server"
)

// Constants defined in cryptobank.capnp.
const (
	AccountSize = uint8(32)
)

type Response struct{ capnp.Struct }

// Response_TypeID is the unique identifier for the type Response.
const Response_TypeID = 0x95b2035e5973395e

func NewResponse(s *capnp.Segment) (Response, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return Response{st}, err
}

func NewRootResponse(s *capnp.Segment) (Response, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return Response{st}, err
}

func ReadRootResponse(msg *capnp.Message) (Response, error) {
	root, err := msg.RootPtr()
	return Response{root.Struct()}, err
}

func (s Response) String() string {
	str, _ := text.Marshal(0x95b2035e5973395e, s.Struct)
	return str
}

func (s Response) Code() int32 {
	return int32(s.Struct.Uint32(0))
}

func (s Response) SetCode(v int32) {
	s.Struct.SetUint32(0, uint32(v))
}

func (s Response) Message() (string, error) {
	p, err := s.Struct.Ptr(0)
	return p.Text(), err
}

func (s Response) HasMessage() bool {
	p, err := s.Struct.Ptr(0)
	return p.IsValid() || err != nil
}

func (s Response) MessageBytes() ([]byte, error) {
	p, err := s.Struct.Ptr(0)
	return p.TextBytes(), err
}

func (s Response) SetMessage(v string) error {
	return s.Struct.SetText(0, v)
}

// Response_List is a list of Response.
type Response_List struct{ capnp.List }

// NewResponse creates a new list of Response.
func NewResponse_List(s *capnp.Segment, sz int32) (Response_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return Response_List{l}, err
}

func (s Response_List) At(i int) Response { return Response{s.List.Struct(i)} }

func (s Response_List) Set(i int, v Response) error { return s.List.SetStruct(i, v.Struct) }

func (s Response_List) String() string {
	str, _ := text.MarshalList(0x95b2035e5973395e, s.List)
	return str
}

// Response_Promise is a wrapper for a Response promised by a client call.
type Response_Promise struct{ *capnp.Pipeline }

func (p Response_Promise) Struct() (Response, error) {
	s, err := p.Pipeline.Struct()
	return Response{s}, err
}

type CoreBanking struct{ Client capnp.Client }

// CoreBanking_TypeID is the unique identifier for the type CoreBanking.
const CoreBanking_TypeID = 0xa5d76bfc3cc292e6

func (c CoreBanking) CreateAccount(ctx context.Context, params func(CoreBanking_createAccount_Params) error, opts ...capnp.CallOption) CoreBanking_createAccount_Results_Promise {
	if c.Client == nil {
		return CoreBanking_createAccount_Results_Promise{Pipeline: capnp.NewPipeline(capnp.ErrorAnswer(capnp.ErrNullClient))}
	}
	call := &capnp.Call{
		Ctx: ctx,
		Method: capnp.Method{
			InterfaceID:   0xa5d76bfc3cc292e6,
			MethodID:      0,
			InterfaceName: "cryptobank/cryptobank.capnp:CoreBanking",
			MethodName:    "createAccount",
		},
		Options: capnp.NewCallOptions(opts),
	}
	if params != nil {
		call.ParamsSize = capnp.ObjectSize{DataSize: 8, PointerCount: 2}
		call.ParamsFunc = func(s capnp.Struct) error { return params(CoreBanking_createAccount_Params{Struct: s}) }
	}
	return CoreBanking_createAccount_Results_Promise{Pipeline: capnp.NewPipeline(c.Client.Call(call))}
}
func (c CoreBanking) DeleteAccount(ctx context.Context, params func(CoreBanking_deleteAccount_Params) error, opts ...capnp.CallOption) CoreBanking_deleteAccount_Results_Promise {
	if c.Client == nil {
		return CoreBanking_deleteAccount_Results_Promise{Pipeline: capnp.NewPipeline(capnp.ErrorAnswer(capnp.ErrNullClient))}
	}
	call := &capnp.Call{
		Ctx: ctx,
		Method: capnp.Method{
			InterfaceID:   0xa5d76bfc3cc292e6,
			MethodID:      1,
			InterfaceName: "cryptobank/cryptobank.capnp:CoreBanking",
			MethodName:    "deleteAccount",
		},
		Options: capnp.NewCallOptions(opts),
	}
	if params != nil {
		call.ParamsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 1}
		call.ParamsFunc = func(s capnp.Struct) error { return params(CoreBanking_deleteAccount_Params{Struct: s}) }
	}
	return CoreBanking_deleteAccount_Results_Promise{Pipeline: capnp.NewPipeline(c.Client.Call(call))}
}
func (c CoreBanking) TransferFunds(ctx context.Context, params func(CoreBanking_transferFunds_Params) error, opts ...capnp.CallOption) CoreBanking_transferFunds_Results_Promise {
	if c.Client == nil {
		return CoreBanking_transferFunds_Results_Promise{Pipeline: capnp.NewPipeline(capnp.ErrorAnswer(capnp.ErrNullClient))}
	}
	call := &capnp.Call{
		Ctx: ctx,
		Method: capnp.Method{
			InterfaceID:   0xa5d76bfc3cc292e6,
			MethodID:      2,
			InterfaceName: "cryptobank/cryptobank.capnp:CoreBanking",
			MethodName:    "transferFunds",
		},
		Options: capnp.NewCallOptions(opts),
	}
	if params != nil {
		call.ParamsSize = capnp.ObjectSize{DataSize: 8, PointerCount: 2}
		call.ParamsFunc = func(s capnp.Struct) error { return params(CoreBanking_transferFunds_Params{Struct: s}) }
	}
	return CoreBanking_transferFunds_Results_Promise{Pipeline: capnp.NewPipeline(c.Client.Call(call))}
}

type CoreBanking_Server interface {
	CreateAccount(CoreBanking_createAccount) error

	DeleteAccount(CoreBanking_deleteAccount) error

	TransferFunds(CoreBanking_transferFunds) error
}

func CoreBanking_ServerToClient(s CoreBanking_Server) CoreBanking {
	c, _ := s.(server.Closer)
	return CoreBanking{Client: server.New(CoreBanking_Methods(nil, s), c)}
}

func CoreBanking_Methods(methods []server.Method, s CoreBanking_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 3)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xa5d76bfc3cc292e6,
			MethodID:      0,
			InterfaceName: "cryptobank/cryptobank.capnp:CoreBanking",
			MethodName:    "createAccount",
		},
		Impl: func(c context.Context, opts capnp.CallOptions, p, r capnp.Struct) error {
			call := CoreBanking_createAccount{c, opts, CoreBanking_createAccount_Params{Struct: p}, CoreBanking_createAccount_Results{Struct: r}}
			return s.CreateAccount(call)
		},
		ResultsSize: capnp.ObjectSize{DataSize: 0, PointerCount: 1},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xa5d76bfc3cc292e6,
			MethodID:      1,
			InterfaceName: "cryptobank/cryptobank.capnp:CoreBanking",
			MethodName:    "deleteAccount",
		},
		Impl: func(c context.Context, opts capnp.CallOptions, p, r capnp.Struct) error {
			call := CoreBanking_deleteAccount{c, opts, CoreBanking_deleteAccount_Params{Struct: p}, CoreBanking_deleteAccount_Results{Struct: r}}
			return s.DeleteAccount(call)
		},
		ResultsSize: capnp.ObjectSize{DataSize: 0, PointerCount: 1},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xa5d76bfc3cc292e6,
			MethodID:      2,
			InterfaceName: "cryptobank/cryptobank.capnp:CoreBanking",
			MethodName:    "transferFunds",
		},
		Impl: func(c context.Context, opts capnp.CallOptions, p, r capnp.Struct) error {
			call := CoreBanking_transferFunds{c, opts, CoreBanking_transferFunds_Params{Struct: p}, CoreBanking_transferFunds_Results{Struct: r}}
			return s.TransferFunds(call)
		},
		ResultsSize: capnp.ObjectSize{DataSize: 0, PointerCount: 1},
	})

	return methods
}

// CoreBanking_createAccount holds the arguments for a server call to CoreBanking.createAccount.
type CoreBanking_createAccount struct {
	Ctx     context.Context
	Options capnp.CallOptions
	Params  CoreBanking_createAccount_Params
	Results CoreBanking_createAccount_Results
}

// CoreBanking_deleteAccount holds the arguments for a server call to CoreBanking.deleteAccount.
type CoreBanking_deleteAccount struct {
	Ctx     context.Context
	Options capnp.CallOptions
	Params  CoreBanking_deleteAccount_Params
	Results CoreBanking_deleteAccount_Results
}

// CoreBanking_transferFunds holds the arguments for a server call to CoreBanking.transferFunds.
type CoreBanking_transferFunds struct {
	Ctx     context.Context
	Options capnp.CallOptions
	Params  CoreBanking_transferFunds_Params
	Results CoreBanking_transferFunds_Results
}

type CoreBanking_createAccount_Params struct{ capnp.Struct }

// CoreBanking_createAccount_Params_TypeID is the unique identifier for the type CoreBanking_createAccount_Params.
const CoreBanking_createAccount_Params_TypeID = 0x924b77e2e5987118

func NewCoreBanking_createAccount_Params(s *capnp.Segment) (CoreBanking_createAccount_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2})
	return CoreBanking_createAccount_Params{st}, err
}

func NewRootCoreBanking_createAccount_Params(s *capnp.Segment) (CoreBanking_createAccount_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2})
	return CoreBanking_createAccount_Params{st}, err
}

func ReadRootCoreBanking_createAccount_Params(msg *capnp.Message) (CoreBanking_createAccount_Params, error) {
	root, err := msg.RootPtr()
	return CoreBanking_createAccount_Params{root.Struct()}, err
}

func (s CoreBanking_createAccount_Params) String() string {
	str, _ := text.Marshal(0x924b77e2e5987118, s.Struct)
	return str
}

func (s CoreBanking_createAccount_Params) AccountId() ([]byte, error) {
	p, err := s.Struct.Ptr(0)
	return []byte(p.Data()), err
}

func (s CoreBanking_createAccount_Params) HasAccountId() bool {
	p, err := s.Struct.Ptr(0)
	return p.IsValid() || err != nil
}

func (s CoreBanking_createAccount_Params) SetAccountId(v []byte) error {
	return s.Struct.SetData(0, v)
}

func (s CoreBanking_createAccount_Params) Name() (string, error) {
	p, err := s.Struct.Ptr(1)
	return p.Text(), err
}

func (s CoreBanking_createAccount_Params) HasName() bool {
	p, err := s.Struct.Ptr(1)
	return p.IsValid() || err != nil
}

func (s CoreBanking_createAccount_Params) NameBytes() ([]byte, error) {
	p, err := s.Struct.Ptr(1)
	return p.TextBytes(), err
}

func (s CoreBanking_createAccount_Params) SetName(v string) error {
	return s.Struct.SetText(1, v)
}

func (s CoreBanking_createAccount_Params) Balance() uint64 {
	return s.Struct.Uint64(0)
}

func (s CoreBanking_createAccount_Params) SetBalance(v uint64) {
	s.Struct.SetUint64(0, v)
}

// CoreBanking_createAccount_Params_List is a list of CoreBanking_createAccount_Params.
type CoreBanking_createAccount_Params_List struct{ capnp.List }

// NewCoreBanking_createAccount_Params creates a new list of CoreBanking_createAccount_Params.
func NewCoreBanking_createAccount_Params_List(s *capnp.Segment, sz int32) (CoreBanking_createAccount_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2}, sz)
	return CoreBanking_createAccount_Params_List{l}, err
}

func (s CoreBanking_createAccount_Params_List) At(i int) CoreBanking_createAccount_Params {
	return CoreBanking_createAccount_Params{s.List.Struct(i)}
}

func (s CoreBanking_createAccount_Params_List) Set(i int, v CoreBanking_createAccount_Params) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s CoreBanking_createAccount_Params_List) String() string {
	str, _ := text.MarshalList(0x924b77e2e5987118, s.List)
	return str
}

// CoreBanking_createAccount_Params_Promise is a wrapper for a CoreBanking_createAccount_Params promised by a client call.
type CoreBanking_createAccount_Params_Promise struct{ *capnp.Pipeline }

func (p CoreBanking_createAccount_Params_Promise) Struct() (CoreBanking_createAccount_Params, error) {
	s, err := p.Pipeline.Struct()
	return CoreBanking_createAccount_Params{s}, err
}

type CoreBanking_createAccount_Results struct{ capnp.Struct }

// CoreBanking_createAccount_Results_TypeID is the unique identifier for the type CoreBanking_createAccount_Results.
const CoreBanking_createAccount_Results_TypeID = 0x831f0a9921d15ba8

func NewCoreBanking_createAccount_Results(s *capnp.Segment) (CoreBanking_createAccount_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return CoreBanking_createAccount_Results{st}, err
}

func NewRootCoreBanking_createAccount_Results(s *capnp.Segment) (CoreBanking_createAccount_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return CoreBanking_createAccount_Results{st}, err
}

func ReadRootCoreBanking_createAccount_Results(msg *capnp.Message) (CoreBanking_createAccount_Results, error) {
	root, err := msg.RootPtr()
	return CoreBanking_createAccount_Results{root.Struct()}, err
}

func (s CoreBanking_createAccount_Results) String() string {
	str, _ := text.Marshal(0x831f0a9921d15ba8, s.Struct)
	return str
}

func (s CoreBanking_createAccount_Results) Res() (Response, error) {
	p, err := s.Struct.Ptr(0)
	return Response{Struct: p.Struct()}, err
}

func (s CoreBanking_createAccount_Results) HasRes() bool {
	p, err := s.Struct.Ptr(0)
	return p.IsValid() || err != nil
}

func (s CoreBanking_createAccount_Results) SetRes(v Response) error {
	return s.Struct.SetPtr(0, v.Struct.ToPtr())
}

// NewRes sets the res field to a newly
// allocated Response struct, preferring placement in s's segment.
func (s CoreBanking_createAccount_Results) NewRes() (Response, error) {
	ss, err := NewResponse(s.Struct.Segment())
	if err != nil {
		return Response{}, err
	}
	err = s.Struct.SetPtr(0, ss.Struct.ToPtr())
	return ss, err
}

// CoreBanking_createAccount_Results_List is a list of CoreBanking_createAccount_Results.
type CoreBanking_createAccount_Results_List struct{ capnp.List }

// NewCoreBanking_createAccount_Results creates a new list of CoreBanking_createAccount_Results.
func NewCoreBanking_createAccount_Results_List(s *capnp.Segment, sz int32) (CoreBanking_createAccount_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return CoreBanking_createAccount_Results_List{l}, err
}

func (s CoreBanking_createAccount_Results_List) At(i int) CoreBanking_createAccount_Results {
	return CoreBanking_createAccount_Results{s.List.Struct(i)}
}

func (s CoreBanking_createAccount_Results_List) Set(i int, v CoreBanking_createAccount_Results) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s CoreBanking_createAccount_Results_List) String() string {
	str, _ := text.MarshalList(0x831f0a9921d15ba8, s.List)
	return str
}

// CoreBanking_createAccount_Results_Promise is a wrapper for a CoreBanking_createAccount_Results promised by a client call.
type CoreBanking_createAccount_Results_Promise struct{ *capnp.Pipeline }

func (p CoreBanking_createAccount_Results_Promise) Struct() (CoreBanking_createAccount_Results, error) {
	s, err := p.Pipeline.Struct()
	return CoreBanking_createAccount_Results{s}, err
}

func (p CoreBanking_createAccount_Results_Promise) Res() Response_Promise {
	return Response_Promise{Pipeline: p.Pipeline.GetPipeline(0)}
}

type CoreBanking_deleteAccount_Params struct{ capnp.Struct }

// CoreBanking_deleteAccount_Params_TypeID is the unique identifier for the type CoreBanking_deleteAccount_Params.
const CoreBanking_deleteAccount_Params_TypeID = 0xf35eac24ee6ad79f

func NewCoreBanking_deleteAccount_Params(s *capnp.Segment) (CoreBanking_deleteAccount_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return CoreBanking_deleteAccount_Params{st}, err
}

func NewRootCoreBanking_deleteAccount_Params(s *capnp.Segment) (CoreBanking_deleteAccount_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return CoreBanking_deleteAccount_Params{st}, err
}

func ReadRootCoreBanking_deleteAccount_Params(msg *capnp.Message) (CoreBanking_deleteAccount_Params, error) {
	root, err := msg.RootPtr()
	return CoreBanking_deleteAccount_Params{root.Struct()}, err
}

func (s CoreBanking_deleteAccount_Params) String() string {
	str, _ := text.Marshal(0xf35eac24ee6ad79f, s.Struct)
	return str
}

func (s CoreBanking_deleteAccount_Params) AccountId() ([]byte, error) {
	p, err := s.Struct.Ptr(0)
	return []byte(p.Data()), err
}

func (s CoreBanking_deleteAccount_Params) HasAccountId() bool {
	p, err := s.Struct.Ptr(0)
	return p.IsValid() || err != nil
}

func (s CoreBanking_deleteAccount_Params) SetAccountId(v []byte) error {
	return s.Struct.SetData(0, v)
}

// CoreBanking_deleteAccount_Params_List is a list of CoreBanking_deleteAccount_Params.
type CoreBanking_deleteAccount_Params_List struct{ capnp.List }

// NewCoreBanking_deleteAccount_Params creates a new list of CoreBanking_deleteAccount_Params.
func NewCoreBanking_deleteAccount_Params_List(s *capnp.Segment, sz int32) (CoreBanking_deleteAccount_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return CoreBanking_deleteAccount_Params_List{l}, err
}

func (s CoreBanking_deleteAccount_Params_List) At(i int) CoreBanking_deleteAccount_Params {
	return CoreBanking_deleteAccount_Params{s.List.Struct(i)}
}

func (s CoreBanking_deleteAccount_Params_List) Set(i int, v CoreBanking_deleteAccount_Params) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s CoreBanking_deleteAccount_Params_List) String() string {
	str, _ := text.MarshalList(0xf35eac24ee6ad79f, s.List)
	return str
}

// CoreBanking_deleteAccount_Params_Promise is a wrapper for a CoreBanking_deleteAccount_Params promised by a client call.
type CoreBanking_deleteAccount_Params_Promise struct{ *capnp.Pipeline }

func (p CoreBanking_deleteAccount_Params_Promise) Struct() (CoreBanking_deleteAccount_Params, error) {
	s, err := p.Pipeline.Struct()
	return CoreBanking_deleteAccount_Params{s}, err
}

type CoreBanking_deleteAccount_Results struct{ capnp.Struct }

// CoreBanking_deleteAccount_Results_TypeID is the unique identifier for the type CoreBanking_deleteAccount_Results.
const CoreBanking_deleteAccount_Results_TypeID = 0x91b913bad4e662a3

func NewCoreBanking_deleteAccount_Results(s *capnp.Segment) (CoreBanking_deleteAccount_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return CoreBanking_deleteAccount_Results{st}, err
}

func NewRootCoreBanking_deleteAccount_Results(s *capnp.Segment) (CoreBanking_deleteAccount_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return CoreBanking_deleteAccount_Results{st}, err
}

func ReadRootCoreBanking_deleteAccount_Results(msg *capnp.Message) (CoreBanking_deleteAccount_Results, error) {
	root, err := msg.RootPtr()
	return CoreBanking_deleteAccount_Results{root.Struct()}, err
}

func (s CoreBanking_deleteAccount_Results) String() string {
	str, _ := text.Marshal(0x91b913bad4e662a3, s.Struct)
	return str
}

func (s CoreBanking_deleteAccount_Results) Res() (Response, error) {
	p, err := s.Struct.Ptr(0)
	return Response{Struct: p.Struct()}, err
}

func (s CoreBanking_deleteAccount_Results) HasRes() bool {
	p, err := s.Struct.Ptr(0)
	return p.IsValid() || err != nil
}

func (s CoreBanking_deleteAccount_Results) SetRes(v Response) error {
	return s.Struct.SetPtr(0, v.Struct.ToPtr())
}

// NewRes sets the res field to a newly
// allocated Response struct, preferring placement in s's segment.
func (s CoreBanking_deleteAccount_Results) NewRes() (Response, error) {
	ss, err := NewResponse(s.Struct.Segment())
	if err != nil {
		return Response{}, err
	}
	err = s.Struct.SetPtr(0, ss.Struct.ToPtr())
	return ss, err
}

// CoreBanking_deleteAccount_Results_List is a list of CoreBanking_deleteAccount_Results.
type CoreBanking_deleteAccount_Results_List struct{ capnp.List }

// NewCoreBanking_deleteAccount_Results creates a new list of CoreBanking_deleteAccount_Results.
func NewCoreBanking_deleteAccount_Results_List(s *capnp.Segment, sz int32) (CoreBanking_deleteAccount_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return CoreBanking_deleteAccount_Results_List{l}, err
}

func (s CoreBanking_deleteAccount_Results_List) At(i int) CoreBanking_deleteAccount_Results {
	return CoreBanking_deleteAccount_Results{s.List.Struct(i)}
}

func (s CoreBanking_deleteAccount_Results_List) Set(i int, v CoreBanking_deleteAccount_Results) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s CoreBanking_deleteAccount_Results_List) String() string {
	str, _ := text.MarshalList(0x91b913bad4e662a3, s.List)
	return str
}

// CoreBanking_deleteAccount_Results_Promise is a wrapper for a CoreBanking_deleteAccount_Results promised by a client call.
type CoreBanking_deleteAccount_Results_Promise struct{ *capnp.Pipeline }

func (p CoreBanking_deleteAccount_Results_Promise) Struct() (CoreBanking_deleteAccount_Results, error) {
	s, err := p.Pipeline.Struct()
	return CoreBanking_deleteAccount_Results{s}, err
}

func (p CoreBanking_deleteAccount_Results_Promise) Res() Response_Promise {
	return Response_Promise{Pipeline: p.Pipeline.GetPipeline(0)}
}

type CoreBanking_transferFunds_Params struct{ capnp.Struct }

// CoreBanking_transferFunds_Params_TypeID is the unique identifier for the type CoreBanking_transferFunds_Params.
const CoreBanking_transferFunds_Params_TypeID = 0xe809bfa702e177ce

func NewCoreBanking_transferFunds_Params(s *capnp.Segment) (CoreBanking_transferFunds_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2})
	return CoreBanking_transferFunds_Params{st}, err
}

func NewRootCoreBanking_transferFunds_Params(s *capnp.Segment) (CoreBanking_transferFunds_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2})
	return CoreBanking_transferFunds_Params{st}, err
}

func ReadRootCoreBanking_transferFunds_Params(msg *capnp.Message) (CoreBanking_transferFunds_Params, error) {
	root, err := msg.RootPtr()
	return CoreBanking_transferFunds_Params{root.Struct()}, err
}

func (s CoreBanking_transferFunds_Params) String() string {
	str, _ := text.Marshal(0xe809bfa702e177ce, s.Struct)
	return str
}

func (s CoreBanking_transferFunds_Params) Source() ([]byte, error) {
	p, err := s.Struct.Ptr(0)
	return []byte(p.Data()), err
}

func (s CoreBanking_transferFunds_Params) HasSource() bool {
	p, err := s.Struct.Ptr(0)
	return p.IsValid() || err != nil
}

func (s CoreBanking_transferFunds_Params) SetSource(v []byte) error {
	return s.Struct.SetData(0, v)
}

func (s CoreBanking_transferFunds_Params) Destination() ([]byte, error) {
	p, err := s.Struct.Ptr(1)
	return []byte(p.Data()), err
}

func (s CoreBanking_transferFunds_Params) HasDestination() bool {
	p, err := s.Struct.Ptr(1)
	return p.IsValid() || err != nil
}

func (s CoreBanking_transferFunds_Params) SetDestination(v []byte) error {
	return s.Struct.SetData(1, v)
}

func (s CoreBanking_transferFunds_Params) Amount() uint64 {
	return s.Struct.Uint64(0)
}

func (s CoreBanking_transferFunds_Params) SetAmount(v uint64) {
	s.Struct.SetUint64(0, v)
}

// CoreBanking_transferFunds_Params_List is a list of CoreBanking_transferFunds_Params.
type CoreBanking_transferFunds_Params_List struct{ capnp.List }

// NewCoreBanking_transferFunds_Params creates a new list of CoreBanking_transferFunds_Params.
func NewCoreBanking_transferFunds_Params_List(s *capnp.Segment, sz int32) (CoreBanking_transferFunds_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2}, sz)
	return CoreBanking_transferFunds_Params_List{l}, err
}

func (s CoreBanking_transferFunds_Params_List) At(i int) CoreBanking_transferFunds_Params {
	return CoreBanking_transferFunds_Params{s.List.Struct(i)}
}

func (s CoreBanking_transferFunds_Params_List) Set(i int, v CoreBanking_transferFunds_Params) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s CoreBanking_transferFunds_Params_List) String() string {
	str, _ := text.MarshalList(0xe809bfa702e177ce, s.List)
	return str
}

// CoreBanking_transferFunds_Params_Promise is a wrapper for a CoreBanking_transferFunds_Params promised by a client call.
type CoreBanking_transferFunds_Params_Promise struct{ *capnp.Pipeline }

func (p CoreBanking_transferFunds_Params_Promise) Struct() (CoreBanking_transferFunds_Params, error) {
	s, err := p.Pipeline.Struct()
	return CoreBanking_transferFunds_Params{s}, err
}

type CoreBanking_transferFunds_Results struct{ capnp.Struct }

// CoreBanking_transferFunds_Results_TypeID is the unique identifier for the type CoreBanking_transferFunds_Results.
const CoreBanking_transferFunds_Results_TypeID = 0x86ab2a31316380b4

func NewCoreBanking_transferFunds_Results(s *capnp.Segment) (CoreBanking_transferFunds_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return CoreBanking_transferFunds_Results{st}, err
}

func NewRootCoreBanking_transferFunds_Results(s *capnp.Segment) (CoreBanking_transferFunds_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return CoreBanking_transferFunds_Results{st}, err
}

func ReadRootCoreBanking_transferFunds_Results(msg *capnp.Message) (CoreBanking_transferFunds_Results, error) {
	root, err := msg.RootPtr()
	return CoreBanking_transferFunds_Results{root.Struct()}, err
}

func (s CoreBanking_transferFunds_Results) String() string {
	str, _ := text.Marshal(0x86ab2a31316380b4, s.Struct)
	return str
}

func (s CoreBanking_transferFunds_Results) Res() (Response, error) {
	p, err := s.Struct.Ptr(0)
	return Response{Struct: p.Struct()}, err
}

func (s CoreBanking_transferFunds_Results) HasRes() bool {
	p, err := s.Struct.Ptr(0)
	return p.IsValid() || err != nil
}

func (s CoreBanking_transferFunds_Results) SetRes(v Response) error {
	return s.Struct.SetPtr(0, v.Struct.ToPtr())
}

// NewRes sets the res field to a newly
// allocated Response struct, preferring placement in s's segment.
func (s CoreBanking_transferFunds_Results) NewRes() (Response, error) {
	ss, err := NewResponse(s.Struct.Segment())
	if err != nil {
		return Response{}, err
	}
	err = s.Struct.SetPtr(0, ss.Struct.ToPtr())
	return ss, err
}

// CoreBanking_transferFunds_Results_List is a list of CoreBanking_transferFunds_Results.
type CoreBanking_transferFunds_Results_List struct{ capnp.List }

// NewCoreBanking_transferFunds_Results creates a new list of CoreBanking_transferFunds_Results.
func NewCoreBanking_transferFunds_Results_List(s *capnp.Segment, sz int32) (CoreBanking_transferFunds_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return CoreBanking_transferFunds_Results_List{l}, err
}

func (s CoreBanking_transferFunds_Results_List) At(i int) CoreBanking_transferFunds_Results {
	return CoreBanking_transferFunds_Results{s.List.Struct(i)}
}

func (s CoreBanking_transferFunds_Results_List) Set(i int, v CoreBanking_transferFunds_Results) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s CoreBanking_transferFunds_Results_List) String() string {
	str, _ := text.MarshalList(0x86ab2a31316380b4, s.List)
	return str
}

// CoreBanking_transferFunds_Results_Promise is a wrapper for a CoreBanking_transferFunds_Results promised by a client call.
type CoreBanking_transferFunds_Results_Promise struct{ *capnp.Pipeline }

func (p CoreBanking_transferFunds_Results_Promise) Struct() (CoreBanking_transferFunds_Results, error) {
	s, err := p.Pipeline.Struct()
	return CoreBanking_transferFunds_Results{s}, err
}

func (p CoreBanking_transferFunds_Results_Promise) Res() Response_Promise {
	return Response_Promise{Pipeline: p.Pipeline.GetPipeline(0)}
}

const schema_85d3acc39d94e0f8 = "x\xda\xbcTMh\x13[\x18\xfd\xce\xbd\x93L\xf3H" +
	"I\x87t\xd1E\x1fy}\xf4A[h_K\xfb\x16" +
	"-O\x12\xe3\x0f\x96V\xc8m\xbb\xb0\x08\x85\xc9\xe4Z" +
	"b\x9aI:\x93P\xea\xa6\x82\xb4\xe0\xc2\x85\xc5B]" +
	"\x14\x17**\x16\x04q\xa3 \x82.D\x04\xc1\x1f\xe8" +
	"J\xb0\x82E\x04\x05u\xe3B\x18\x99\xc4IR\x0cb" +
	"\x15\xdc]\xee=|\xe7|\xdf9\xdf\xed\xbd\x8d\x18\xeb" +
	"\xf3-(Db\xc0\xe7w.\x1f~\xdcv\xf6\x8f\xc8" +
	"\x09\xd2:@\xe4\x83J\xd4\xff\x0f\xfb\x00Bx\x90E" +
	"\x09\xce\x8d\xe3F__\xd7\xd5\xa5Z\xc0d\x19\x90-" +
	"\x01\x1e\x8e\x8eL0\xeb\xc9\x12i\xad\x8a\xf3\xe9\xc5\x99" +
	"\xb5{\xebO\x17\x89\xd0\x7f\x8a\xc5\x11^c*\xd1\xf8" +
	"*\xe3\x18\xbf\xc0\x18\x88\x9c\xf3\xc9\xadg\xb7\xc27O" +
	"\xd7\x16\\)\x17\xbcR*\xd82\xbb\xfa\xea\xe5\xdc\xc8" +
	"2\x89\x0e\xb8\x08\xb7B\xff\x03\xf6\xc6E<g\xd7\x08" +
	"\xce\xd4\xa0=9\xc5\xaf\xaf\x90h\x05\xaa\x9c\xe5Z\xf3" +
	"\xbc\x0b\xe1\x93\\%\x0a/\xf29\x82\xb3\xb5|\xf7\xff" +
	"\xcf\x99\x8d\x8b\xa4\xb5\xf2m\x027y\x1c\xe1\xf7%\xe4" +
	"[~?<\xab\xa8D\xce\xa3\xb9Mv\xe9N\xe0\xf5" +
	"6\xf6I\xa5\xc4\x9eU\\\xf6s\x1bG\xdf\xb5\xafO" +
	"}\xacm \xe0+\x01\xfe\xf4E\xa9\xdb1\xac\xf9|" +
	"!\x97\xd4\xfdf\xe6_\xeflfz\x0c=o\xe6\x87" +
	"\xf6\xe4,\x19\xd7\xcdL\xda\x9c\xee1,\xa9\x17\xe4n" +
	"\xc3\xc8\x15\xcdB\xfb\x98\x8c\xd8\xc5\x99\x82-\x14\xae\x10" +
	") \xd2\x1a\xff&\x12\x0d\x1c\xa2\x99A\xb5\xa4\x8d\xa6" +
	"j\xef\x044\x11~\x9c\xac`\xe9\xa6}DZ\xfb\x8b" +
	"f\xca\xfeE2\xa5\x1e\x99^\xeec<}LR\x02" +
	"\x80\x9f\x98\xcf\xff\xd7N$\xa6\xe4\x8c\xfcm\xf3\xd8>" +
	"\xfc\x84\x1e\xb2\xf4\xac-\x82\x15\xae}cDb/\x87" +
	"H0h@\xb3\x9b\x06\xed`\x17\x918\xc0!&\x18" +
	"\xc0\x9a\xc1\x884\x11'\x12\xa3\x1c\xe2\x10\x83\xf3u\x08" +
	"\xc3\x84\x14\x1a\x89\xa1\x91\x102\xf5\xacD\x90\x18\x82\x84" +
	"\x85\xa4>\xa3\x9b\x86D\x80\x18\x025zy=\xbdc" +
	"\xd2\xce\x87r\xa6-\x13\x80h\xa8H\xebtU\xb4s" +
	"\x88^\x06OY\xb7\xab\xa2\x83C\x0c0\x84\x8c\\J" +
	"B!\x06\x85\xb0\x90\x95\xb6\xadOW\x14|\xdf\xc4\x9a" +
	"\x09\xb9&\x8a \xf7\x11UV\x12\xdew\xa1\x09\x8b\x98" +
	"6\xac\xa2\xba\x0e\xf0\x16[\xdb\xe5\xbe\xfd\xa7\x82U\x96" +
	"\x09\xde/\xa2u\xbaom\xaa\xe3M\x9f\"\xa5y\xc5" +
	"\xe0x\xe6Wo\xbc\xc4R\xa4\x94\xd9\x18\x12\xf8\xe9\xbc" +
	"\xd7\xf1w\x88H\xc48\xc4h\x8d\xbf\xc3\xc9:\xfe\x0e" +
	"U\xfd\x8d\xda\xb9\xa2eH\xcfZ'%\xedB\xda\xd4" +
	"\x0b\xa4\xa6s\xa6w\x1b\xd5\xb3n\x07\xdfX\xbc\xc3\xfc" +
	"{\x92k\xe2\xefF2\xc8!Z\xea'\xedK\x00\x00" +
	"\x00\xff\xffw\x08\xa2%"

func init() {
	schemas.Register(schema_85d3acc39d94e0f8,
		0x831f0a9921d15ba8,
		0x86ab2a31316380b4,
		0x86d27202544b4ccb,
		0x91b913bad4e662a3,
		0x924b77e2e5987118,
		0x95b2035e5973395e,
		0xa5d76bfc3cc292e6,
		0xe809bfa702e177ce,
		0xf35eac24ee6ad79f)
}
