// Code generated by capnpc-go. DO NOT EDIT.

package cryptobank

import (
	context "golang.org/x/net/context"
	capnp "zombiezen.com/go/capnproto2"
	text "zombiezen.com/go/capnproto2/encoding/text"
	schemas "zombiezen.com/go/capnproto2/schemas"
	server "zombiezen.com/go/capnproto2/server"
)

// Constants defined in cryptobank.capnp.
const (
	AccountSize = uint8(32)
)

type Response struct{ capnp.Struct }

// Response_TypeID is the unique identifier for the type Response.
const Response_TypeID = 0xe16a5fbf7cc9b4b2

func NewResponse(s *capnp.Segment) (Response, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return Response{st}, err
}

func NewRootResponse(s *capnp.Segment) (Response, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return Response{st}, err
}

func ReadRootResponse(msg *capnp.Message) (Response, error) {
	root, err := msg.RootPtr()
	return Response{root.Struct()}, err
}

func (s Response) String() string {
	str, _ := text.Marshal(0xe16a5fbf7cc9b4b2, s.Struct)
	return str
}

func (s Response) Code() int32 {
	return int32(s.Struct.Uint32(0))
}

func (s Response) SetCode(v int32) {
	s.Struct.SetUint32(0, uint32(v))
}

func (s Response) Message() (string, error) {
	p, err := s.Struct.Ptr(0)
	return p.Text(), err
}

func (s Response) HasMessage() bool {
	p, err := s.Struct.Ptr(0)
	return p.IsValid() || err != nil
}

func (s Response) MessageBytes() ([]byte, error) {
	p, err := s.Struct.Ptr(0)
	return p.TextBytes(), err
}

func (s Response) SetMessage(v string) error {
	return s.Struct.SetText(0, v)
}

// Response_List is a list of Response.
type Response_List struct{ capnp.List }

// NewResponse creates a new list of Response.
func NewResponse_List(s *capnp.Segment, sz int32) (Response_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return Response_List{l}, err
}

func (s Response_List) At(i int) Response { return Response{s.List.Struct(i)} }

func (s Response_List) Set(i int, v Response) error { return s.List.SetStruct(i, v.Struct) }

func (s Response_List) String() string {
	str, _ := text.MarshalList(0xe16a5fbf7cc9b4b2, s.List)
	return str
}

// Response_Promise is a wrapper for a Response promised by a client call.
type Response_Promise struct{ *capnp.Pipeline }

func (p Response_Promise) Struct() (Response, error) {
	s, err := p.Pipeline.Struct()
	return Response{s}, err
}

type CoreBanking struct{ Client capnp.Client }

// CoreBanking_TypeID is the unique identifier for the type CoreBanking.
const CoreBanking_TypeID = 0xa98297869266ae45

func (c CoreBanking) CreateAccount(ctx context.Context, params func(CoreBanking_createAccount_Params) error, opts ...capnp.CallOption) CoreBanking_createAccount_Results_Promise {
	if c.Client == nil {
		return CoreBanking_createAccount_Results_Promise{Pipeline: capnp.NewPipeline(capnp.ErrorAnswer(capnp.ErrNullClient))}
	}
	call := &capnp.Call{
		Ctx: ctx,
		Method: capnp.Method{
			InterfaceID:   0xa98297869266ae45,
			MethodID:      0,
			InterfaceName: "cryptobank/cryptobank.capnp:CoreBanking",
			MethodName:    "createAccount",
		},
		Options: capnp.NewCallOptions(opts),
	}
	if params != nil {
		call.ParamsSize = capnp.ObjectSize{DataSize: 8, PointerCount: 2}
		call.ParamsFunc = func(s capnp.Struct) error { return params(CoreBanking_createAccount_Params{Struct: s}) }
	}
	return CoreBanking_createAccount_Results_Promise{Pipeline: capnp.NewPipeline(c.Client.Call(call))}
}
func (c CoreBanking) DeleteAccount(ctx context.Context, params func(CoreBanking_deleteAccount_Params) error, opts ...capnp.CallOption) CoreBanking_deleteAccount_Results_Promise {
	if c.Client == nil {
		return CoreBanking_deleteAccount_Results_Promise{Pipeline: capnp.NewPipeline(capnp.ErrorAnswer(capnp.ErrNullClient))}
	}
	call := &capnp.Call{
		Ctx: ctx,
		Method: capnp.Method{
			InterfaceID:   0xa98297869266ae45,
			MethodID:      1,
			InterfaceName: "cryptobank/cryptobank.capnp:CoreBanking",
			MethodName:    "deleteAccount",
		},
		Options: capnp.NewCallOptions(opts),
	}
	if params != nil {
		call.ParamsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 1}
		call.ParamsFunc = func(s capnp.Struct) error { return params(CoreBanking_deleteAccount_Params{Struct: s}) }
	}
	return CoreBanking_deleteAccount_Results_Promise{Pipeline: capnp.NewPipeline(c.Client.Call(call))}
}
func (c CoreBanking) TransferFunds(ctx context.Context, params func(CoreBanking_transferFunds_Params) error, opts ...capnp.CallOption) CoreBanking_transferFunds_Results_Promise {
	if c.Client == nil {
		return CoreBanking_transferFunds_Results_Promise{Pipeline: capnp.NewPipeline(capnp.ErrorAnswer(capnp.ErrNullClient))}
	}
	call := &capnp.Call{
		Ctx: ctx,
		Method: capnp.Method{
			InterfaceID:   0xa98297869266ae45,
			MethodID:      2,
			InterfaceName: "cryptobank/cryptobank.capnp:CoreBanking",
			MethodName:    "transferFunds",
		},
		Options: capnp.NewCallOptions(opts),
	}
	if params != nil {
		call.ParamsSize = capnp.ObjectSize{DataSize: 8, PointerCount: 2}
		call.ParamsFunc = func(s capnp.Struct) error { return params(CoreBanking_transferFunds_Params{Struct: s}) }
	}
	return CoreBanking_transferFunds_Results_Promise{Pipeline: capnp.NewPipeline(c.Client.Call(call))}
}
func (c CoreBanking) GetAccountInfo(ctx context.Context, params func(CoreBanking_getAccountInfo_Params) error, opts ...capnp.CallOption) CoreBanking_getAccountInfo_Results_Promise {
	if c.Client == nil {
		return CoreBanking_getAccountInfo_Results_Promise{Pipeline: capnp.NewPipeline(capnp.ErrorAnswer(capnp.ErrNullClient))}
	}
	call := &capnp.Call{
		Ctx: ctx,
		Method: capnp.Method{
			InterfaceID:   0xa98297869266ae45,
			MethodID:      3,
			InterfaceName: "cryptobank/cryptobank.capnp:CoreBanking",
			MethodName:    "getAccountInfo",
		},
		Options: capnp.NewCallOptions(opts),
	}
	if params != nil {
		call.ParamsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 1}
		call.ParamsFunc = func(s capnp.Struct) error { return params(CoreBanking_getAccountInfo_Params{Struct: s}) }
	}
	return CoreBanking_getAccountInfo_Results_Promise{Pipeline: capnp.NewPipeline(c.Client.Call(call))}
}

type CoreBanking_Server interface {
	CreateAccount(CoreBanking_createAccount) error

	DeleteAccount(CoreBanking_deleteAccount) error

	TransferFunds(CoreBanking_transferFunds) error

	GetAccountInfo(CoreBanking_getAccountInfo) error
}

func CoreBanking_ServerToClient(s CoreBanking_Server) CoreBanking {
	c, _ := s.(server.Closer)
	return CoreBanking{Client: server.New(CoreBanking_Methods(nil, s), c)}
}

func CoreBanking_Methods(methods []server.Method, s CoreBanking_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 4)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xa98297869266ae45,
			MethodID:      0,
			InterfaceName: "cryptobank/cryptobank.capnp:CoreBanking",
			MethodName:    "createAccount",
		},
		Impl: func(c context.Context, opts capnp.CallOptions, p, r capnp.Struct) error {
			call := CoreBanking_createAccount{c, opts, CoreBanking_createAccount_Params{Struct: p}, CoreBanking_createAccount_Results{Struct: r}}
			return s.CreateAccount(call)
		},
		ResultsSize: capnp.ObjectSize{DataSize: 0, PointerCount: 1},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xa98297869266ae45,
			MethodID:      1,
			InterfaceName: "cryptobank/cryptobank.capnp:CoreBanking",
			MethodName:    "deleteAccount",
		},
		Impl: func(c context.Context, opts capnp.CallOptions, p, r capnp.Struct) error {
			call := CoreBanking_deleteAccount{c, opts, CoreBanking_deleteAccount_Params{Struct: p}, CoreBanking_deleteAccount_Results{Struct: r}}
			return s.DeleteAccount(call)
		},
		ResultsSize: capnp.ObjectSize{DataSize: 0, PointerCount: 1},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xa98297869266ae45,
			MethodID:      2,
			InterfaceName: "cryptobank/cryptobank.capnp:CoreBanking",
			MethodName:    "transferFunds",
		},
		Impl: func(c context.Context, opts capnp.CallOptions, p, r capnp.Struct) error {
			call := CoreBanking_transferFunds{c, opts, CoreBanking_transferFunds_Params{Struct: p}, CoreBanking_transferFunds_Results{Struct: r}}
			return s.TransferFunds(call)
		},
		ResultsSize: capnp.ObjectSize{DataSize: 0, PointerCount: 1},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xa98297869266ae45,
			MethodID:      3,
			InterfaceName: "cryptobank/cryptobank.capnp:CoreBanking",
			MethodName:    "getAccountInfo",
		},
		Impl: func(c context.Context, opts capnp.CallOptions, p, r capnp.Struct) error {
			call := CoreBanking_getAccountInfo{c, opts, CoreBanking_getAccountInfo_Params{Struct: p}, CoreBanking_getAccountInfo_Results{Struct: r}}
			return s.GetAccountInfo(call)
		},
		ResultsSize: capnp.ObjectSize{DataSize: 8, PointerCount: 2},
	})

	return methods
}

// CoreBanking_createAccount holds the arguments for a server call to CoreBanking.createAccount.
type CoreBanking_createAccount struct {
	Ctx     context.Context
	Options capnp.CallOptions
	Params  CoreBanking_createAccount_Params
	Results CoreBanking_createAccount_Results
}

// CoreBanking_deleteAccount holds the arguments for a server call to CoreBanking.deleteAccount.
type CoreBanking_deleteAccount struct {
	Ctx     context.Context
	Options capnp.CallOptions
	Params  CoreBanking_deleteAccount_Params
	Results CoreBanking_deleteAccount_Results
}

// CoreBanking_transferFunds holds the arguments for a server call to CoreBanking.transferFunds.
type CoreBanking_transferFunds struct {
	Ctx     context.Context
	Options capnp.CallOptions
	Params  CoreBanking_transferFunds_Params
	Results CoreBanking_transferFunds_Results
}

// CoreBanking_getAccountInfo holds the arguments for a server call to CoreBanking.getAccountInfo.
type CoreBanking_getAccountInfo struct {
	Ctx     context.Context
	Options capnp.CallOptions
	Params  CoreBanking_getAccountInfo_Params
	Results CoreBanking_getAccountInfo_Results
}

type CoreBanking_createAccount_Params struct{ capnp.Struct }

// CoreBanking_createAccount_Params_TypeID is the unique identifier for the type CoreBanking_createAccount_Params.
const CoreBanking_createAccount_Params_TypeID = 0xf679d46bf8232843

func NewCoreBanking_createAccount_Params(s *capnp.Segment) (CoreBanking_createAccount_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2})
	return CoreBanking_createAccount_Params{st}, err
}

func NewRootCoreBanking_createAccount_Params(s *capnp.Segment) (CoreBanking_createAccount_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2})
	return CoreBanking_createAccount_Params{st}, err
}

func ReadRootCoreBanking_createAccount_Params(msg *capnp.Message) (CoreBanking_createAccount_Params, error) {
	root, err := msg.RootPtr()
	return CoreBanking_createAccount_Params{root.Struct()}, err
}

func (s CoreBanking_createAccount_Params) String() string {
	str, _ := text.Marshal(0xf679d46bf8232843, s.Struct)
	return str
}

func (s CoreBanking_createAccount_Params) AccountId() ([]byte, error) {
	p, err := s.Struct.Ptr(0)
	return []byte(p.Data()), err
}

func (s CoreBanking_createAccount_Params) HasAccountId() bool {
	p, err := s.Struct.Ptr(0)
	return p.IsValid() || err != nil
}

func (s CoreBanking_createAccount_Params) SetAccountId(v []byte) error {
	return s.Struct.SetData(0, v)
}

func (s CoreBanking_createAccount_Params) Name() (string, error) {
	p, err := s.Struct.Ptr(1)
	return p.Text(), err
}

func (s CoreBanking_createAccount_Params) HasName() bool {
	p, err := s.Struct.Ptr(1)
	return p.IsValid() || err != nil
}

func (s CoreBanking_createAccount_Params) NameBytes() ([]byte, error) {
	p, err := s.Struct.Ptr(1)
	return p.TextBytes(), err
}

func (s CoreBanking_createAccount_Params) SetName(v string) error {
	return s.Struct.SetText(1, v)
}

func (s CoreBanking_createAccount_Params) Balance() uint64 {
	return s.Struct.Uint64(0)
}

func (s CoreBanking_createAccount_Params) SetBalance(v uint64) {
	s.Struct.SetUint64(0, v)
}

// CoreBanking_createAccount_Params_List is a list of CoreBanking_createAccount_Params.
type CoreBanking_createAccount_Params_List struct{ capnp.List }

// NewCoreBanking_createAccount_Params creates a new list of CoreBanking_createAccount_Params.
func NewCoreBanking_createAccount_Params_List(s *capnp.Segment, sz int32) (CoreBanking_createAccount_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2}, sz)
	return CoreBanking_createAccount_Params_List{l}, err
}

func (s CoreBanking_createAccount_Params_List) At(i int) CoreBanking_createAccount_Params {
	return CoreBanking_createAccount_Params{s.List.Struct(i)}
}

func (s CoreBanking_createAccount_Params_List) Set(i int, v CoreBanking_createAccount_Params) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s CoreBanking_createAccount_Params_List) String() string {
	str, _ := text.MarshalList(0xf679d46bf8232843, s.List)
	return str
}

// CoreBanking_createAccount_Params_Promise is a wrapper for a CoreBanking_createAccount_Params promised by a client call.
type CoreBanking_createAccount_Params_Promise struct{ *capnp.Pipeline }

func (p CoreBanking_createAccount_Params_Promise) Struct() (CoreBanking_createAccount_Params, error) {
	s, err := p.Pipeline.Struct()
	return CoreBanking_createAccount_Params{s}, err
}

type CoreBanking_createAccount_Results struct{ capnp.Struct }

// CoreBanking_createAccount_Results_TypeID is the unique identifier for the type CoreBanking_createAccount_Results.
const CoreBanking_createAccount_Results_TypeID = 0xbae40ac2ebeb62eb

func NewCoreBanking_createAccount_Results(s *capnp.Segment) (CoreBanking_createAccount_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return CoreBanking_createAccount_Results{st}, err
}

func NewRootCoreBanking_createAccount_Results(s *capnp.Segment) (CoreBanking_createAccount_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return CoreBanking_createAccount_Results{st}, err
}

func ReadRootCoreBanking_createAccount_Results(msg *capnp.Message) (CoreBanking_createAccount_Results, error) {
	root, err := msg.RootPtr()
	return CoreBanking_createAccount_Results{root.Struct()}, err
}

func (s CoreBanking_createAccount_Results) String() string {
	str, _ := text.Marshal(0xbae40ac2ebeb62eb, s.Struct)
	return str
}

func (s CoreBanking_createAccount_Results) Res() (Response, error) {
	p, err := s.Struct.Ptr(0)
	return Response{Struct: p.Struct()}, err
}

func (s CoreBanking_createAccount_Results) HasRes() bool {
	p, err := s.Struct.Ptr(0)
	return p.IsValid() || err != nil
}

func (s CoreBanking_createAccount_Results) SetRes(v Response) error {
	return s.Struct.SetPtr(0, v.Struct.ToPtr())
}

// NewRes sets the res field to a newly
// allocated Response struct, preferring placement in s's segment.
func (s CoreBanking_createAccount_Results) NewRes() (Response, error) {
	ss, err := NewResponse(s.Struct.Segment())
	if err != nil {
		return Response{}, err
	}
	err = s.Struct.SetPtr(0, ss.Struct.ToPtr())
	return ss, err
}

// CoreBanking_createAccount_Results_List is a list of CoreBanking_createAccount_Results.
type CoreBanking_createAccount_Results_List struct{ capnp.List }

// NewCoreBanking_createAccount_Results creates a new list of CoreBanking_createAccount_Results.
func NewCoreBanking_createAccount_Results_List(s *capnp.Segment, sz int32) (CoreBanking_createAccount_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return CoreBanking_createAccount_Results_List{l}, err
}

func (s CoreBanking_createAccount_Results_List) At(i int) CoreBanking_createAccount_Results {
	return CoreBanking_createAccount_Results{s.List.Struct(i)}
}

func (s CoreBanking_createAccount_Results_List) Set(i int, v CoreBanking_createAccount_Results) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s CoreBanking_createAccount_Results_List) String() string {
	str, _ := text.MarshalList(0xbae40ac2ebeb62eb, s.List)
	return str
}

// CoreBanking_createAccount_Results_Promise is a wrapper for a CoreBanking_createAccount_Results promised by a client call.
type CoreBanking_createAccount_Results_Promise struct{ *capnp.Pipeline }

func (p CoreBanking_createAccount_Results_Promise) Struct() (CoreBanking_createAccount_Results, error) {
	s, err := p.Pipeline.Struct()
	return CoreBanking_createAccount_Results{s}, err
}

func (p CoreBanking_createAccount_Results_Promise) Res() Response_Promise {
	return Response_Promise{Pipeline: p.Pipeline.GetPipeline(0)}
}

type CoreBanking_deleteAccount_Params struct{ capnp.Struct }

// CoreBanking_deleteAccount_Params_TypeID is the unique identifier for the type CoreBanking_deleteAccount_Params.
const CoreBanking_deleteAccount_Params_TypeID = 0xf09ba84d3893ec83

func NewCoreBanking_deleteAccount_Params(s *capnp.Segment) (CoreBanking_deleteAccount_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return CoreBanking_deleteAccount_Params{st}, err
}

func NewRootCoreBanking_deleteAccount_Params(s *capnp.Segment) (CoreBanking_deleteAccount_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return CoreBanking_deleteAccount_Params{st}, err
}

func ReadRootCoreBanking_deleteAccount_Params(msg *capnp.Message) (CoreBanking_deleteAccount_Params, error) {
	root, err := msg.RootPtr()
	return CoreBanking_deleteAccount_Params{root.Struct()}, err
}

func (s CoreBanking_deleteAccount_Params) String() string {
	str, _ := text.Marshal(0xf09ba84d3893ec83, s.Struct)
	return str
}

func (s CoreBanking_deleteAccount_Params) AccountId() ([]byte, error) {
	p, err := s.Struct.Ptr(0)
	return []byte(p.Data()), err
}

func (s CoreBanking_deleteAccount_Params) HasAccountId() bool {
	p, err := s.Struct.Ptr(0)
	return p.IsValid() || err != nil
}

func (s CoreBanking_deleteAccount_Params) SetAccountId(v []byte) error {
	return s.Struct.SetData(0, v)
}

// CoreBanking_deleteAccount_Params_List is a list of CoreBanking_deleteAccount_Params.
type CoreBanking_deleteAccount_Params_List struct{ capnp.List }

// NewCoreBanking_deleteAccount_Params creates a new list of CoreBanking_deleteAccount_Params.
func NewCoreBanking_deleteAccount_Params_List(s *capnp.Segment, sz int32) (CoreBanking_deleteAccount_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return CoreBanking_deleteAccount_Params_List{l}, err
}

func (s CoreBanking_deleteAccount_Params_List) At(i int) CoreBanking_deleteAccount_Params {
	return CoreBanking_deleteAccount_Params{s.List.Struct(i)}
}

func (s CoreBanking_deleteAccount_Params_List) Set(i int, v CoreBanking_deleteAccount_Params) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s CoreBanking_deleteAccount_Params_List) String() string {
	str, _ := text.MarshalList(0xf09ba84d3893ec83, s.List)
	return str
}

// CoreBanking_deleteAccount_Params_Promise is a wrapper for a CoreBanking_deleteAccount_Params promised by a client call.
type CoreBanking_deleteAccount_Params_Promise struct{ *capnp.Pipeline }

func (p CoreBanking_deleteAccount_Params_Promise) Struct() (CoreBanking_deleteAccount_Params, error) {
	s, err := p.Pipeline.Struct()
	return CoreBanking_deleteAccount_Params{s}, err
}

type CoreBanking_deleteAccount_Results struct{ capnp.Struct }

// CoreBanking_deleteAccount_Results_TypeID is the unique identifier for the type CoreBanking_deleteAccount_Results.
const CoreBanking_deleteAccount_Results_TypeID = 0xe7c119336e126854

func NewCoreBanking_deleteAccount_Results(s *capnp.Segment) (CoreBanking_deleteAccount_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return CoreBanking_deleteAccount_Results{st}, err
}

func NewRootCoreBanking_deleteAccount_Results(s *capnp.Segment) (CoreBanking_deleteAccount_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return CoreBanking_deleteAccount_Results{st}, err
}

func ReadRootCoreBanking_deleteAccount_Results(msg *capnp.Message) (CoreBanking_deleteAccount_Results, error) {
	root, err := msg.RootPtr()
	return CoreBanking_deleteAccount_Results{root.Struct()}, err
}

func (s CoreBanking_deleteAccount_Results) String() string {
	str, _ := text.Marshal(0xe7c119336e126854, s.Struct)
	return str
}

func (s CoreBanking_deleteAccount_Results) Res() (Response, error) {
	p, err := s.Struct.Ptr(0)
	return Response{Struct: p.Struct()}, err
}

func (s CoreBanking_deleteAccount_Results) HasRes() bool {
	p, err := s.Struct.Ptr(0)
	return p.IsValid() || err != nil
}

func (s CoreBanking_deleteAccount_Results) SetRes(v Response) error {
	return s.Struct.SetPtr(0, v.Struct.ToPtr())
}

// NewRes sets the res field to a newly
// allocated Response struct, preferring placement in s's segment.
func (s CoreBanking_deleteAccount_Results) NewRes() (Response, error) {
	ss, err := NewResponse(s.Struct.Segment())
	if err != nil {
		return Response{}, err
	}
	err = s.Struct.SetPtr(0, ss.Struct.ToPtr())
	return ss, err
}

// CoreBanking_deleteAccount_Results_List is a list of CoreBanking_deleteAccount_Results.
type CoreBanking_deleteAccount_Results_List struct{ capnp.List }

// NewCoreBanking_deleteAccount_Results creates a new list of CoreBanking_deleteAccount_Results.
func NewCoreBanking_deleteAccount_Results_List(s *capnp.Segment, sz int32) (CoreBanking_deleteAccount_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return CoreBanking_deleteAccount_Results_List{l}, err
}

func (s CoreBanking_deleteAccount_Results_List) At(i int) CoreBanking_deleteAccount_Results {
	return CoreBanking_deleteAccount_Results{s.List.Struct(i)}
}

func (s CoreBanking_deleteAccount_Results_List) Set(i int, v CoreBanking_deleteAccount_Results) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s CoreBanking_deleteAccount_Results_List) String() string {
	str, _ := text.MarshalList(0xe7c119336e126854, s.List)
	return str
}

// CoreBanking_deleteAccount_Results_Promise is a wrapper for a CoreBanking_deleteAccount_Results promised by a client call.
type CoreBanking_deleteAccount_Results_Promise struct{ *capnp.Pipeline }

func (p CoreBanking_deleteAccount_Results_Promise) Struct() (CoreBanking_deleteAccount_Results, error) {
	s, err := p.Pipeline.Struct()
	return CoreBanking_deleteAccount_Results{s}, err
}

func (p CoreBanking_deleteAccount_Results_Promise) Res() Response_Promise {
	return Response_Promise{Pipeline: p.Pipeline.GetPipeline(0)}
}

type CoreBanking_transferFunds_Params struct{ capnp.Struct }

// CoreBanking_transferFunds_Params_TypeID is the unique identifier for the type CoreBanking_transferFunds_Params.
const CoreBanking_transferFunds_Params_TypeID = 0xf2e0a5a1bd186b0c

func NewCoreBanking_transferFunds_Params(s *capnp.Segment) (CoreBanking_transferFunds_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2})
	return CoreBanking_transferFunds_Params{st}, err
}

func NewRootCoreBanking_transferFunds_Params(s *capnp.Segment) (CoreBanking_transferFunds_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2})
	return CoreBanking_transferFunds_Params{st}, err
}

func ReadRootCoreBanking_transferFunds_Params(msg *capnp.Message) (CoreBanking_transferFunds_Params, error) {
	root, err := msg.RootPtr()
	return CoreBanking_transferFunds_Params{root.Struct()}, err
}

func (s CoreBanking_transferFunds_Params) String() string {
	str, _ := text.Marshal(0xf2e0a5a1bd186b0c, s.Struct)
	return str
}

func (s CoreBanking_transferFunds_Params) Source() ([]byte, error) {
	p, err := s.Struct.Ptr(0)
	return []byte(p.Data()), err
}

func (s CoreBanking_transferFunds_Params) HasSource() bool {
	p, err := s.Struct.Ptr(0)
	return p.IsValid() || err != nil
}

func (s CoreBanking_transferFunds_Params) SetSource(v []byte) error {
	return s.Struct.SetData(0, v)
}

func (s CoreBanking_transferFunds_Params) Destination() ([]byte, error) {
	p, err := s.Struct.Ptr(1)
	return []byte(p.Data()), err
}

func (s CoreBanking_transferFunds_Params) HasDestination() bool {
	p, err := s.Struct.Ptr(1)
	return p.IsValid() || err != nil
}

func (s CoreBanking_transferFunds_Params) SetDestination(v []byte) error {
	return s.Struct.SetData(1, v)
}

func (s CoreBanking_transferFunds_Params) Amount() uint64 {
	return s.Struct.Uint64(0)
}

func (s CoreBanking_transferFunds_Params) SetAmount(v uint64) {
	s.Struct.SetUint64(0, v)
}

// CoreBanking_transferFunds_Params_List is a list of CoreBanking_transferFunds_Params.
type CoreBanking_transferFunds_Params_List struct{ capnp.List }

// NewCoreBanking_transferFunds_Params creates a new list of CoreBanking_transferFunds_Params.
func NewCoreBanking_transferFunds_Params_List(s *capnp.Segment, sz int32) (CoreBanking_transferFunds_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2}, sz)
	return CoreBanking_transferFunds_Params_List{l}, err
}

func (s CoreBanking_transferFunds_Params_List) At(i int) CoreBanking_transferFunds_Params {
	return CoreBanking_transferFunds_Params{s.List.Struct(i)}
}

func (s CoreBanking_transferFunds_Params_List) Set(i int, v CoreBanking_transferFunds_Params) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s CoreBanking_transferFunds_Params_List) String() string {
	str, _ := text.MarshalList(0xf2e0a5a1bd186b0c, s.List)
	return str
}

// CoreBanking_transferFunds_Params_Promise is a wrapper for a CoreBanking_transferFunds_Params promised by a client call.
type CoreBanking_transferFunds_Params_Promise struct{ *capnp.Pipeline }

func (p CoreBanking_transferFunds_Params_Promise) Struct() (CoreBanking_transferFunds_Params, error) {
	s, err := p.Pipeline.Struct()
	return CoreBanking_transferFunds_Params{s}, err
}

type CoreBanking_transferFunds_Results struct{ capnp.Struct }

// CoreBanking_transferFunds_Results_TypeID is the unique identifier for the type CoreBanking_transferFunds_Results.
const CoreBanking_transferFunds_Results_TypeID = 0x951f644a900fb6e8

func NewCoreBanking_transferFunds_Results(s *capnp.Segment) (CoreBanking_transferFunds_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return CoreBanking_transferFunds_Results{st}, err
}

func NewRootCoreBanking_transferFunds_Results(s *capnp.Segment) (CoreBanking_transferFunds_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return CoreBanking_transferFunds_Results{st}, err
}

func ReadRootCoreBanking_transferFunds_Results(msg *capnp.Message) (CoreBanking_transferFunds_Results, error) {
	root, err := msg.RootPtr()
	return CoreBanking_transferFunds_Results{root.Struct()}, err
}

func (s CoreBanking_transferFunds_Results) String() string {
	str, _ := text.Marshal(0x951f644a900fb6e8, s.Struct)
	return str
}

func (s CoreBanking_transferFunds_Results) Res() (Response, error) {
	p, err := s.Struct.Ptr(0)
	return Response{Struct: p.Struct()}, err
}

func (s CoreBanking_transferFunds_Results) HasRes() bool {
	p, err := s.Struct.Ptr(0)
	return p.IsValid() || err != nil
}

func (s CoreBanking_transferFunds_Results) SetRes(v Response) error {
	return s.Struct.SetPtr(0, v.Struct.ToPtr())
}

// NewRes sets the res field to a newly
// allocated Response struct, preferring placement in s's segment.
func (s CoreBanking_transferFunds_Results) NewRes() (Response, error) {
	ss, err := NewResponse(s.Struct.Segment())
	if err != nil {
		return Response{}, err
	}
	err = s.Struct.SetPtr(0, ss.Struct.ToPtr())
	return ss, err
}

// CoreBanking_transferFunds_Results_List is a list of CoreBanking_transferFunds_Results.
type CoreBanking_transferFunds_Results_List struct{ capnp.List }

// NewCoreBanking_transferFunds_Results creates a new list of CoreBanking_transferFunds_Results.
func NewCoreBanking_transferFunds_Results_List(s *capnp.Segment, sz int32) (CoreBanking_transferFunds_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return CoreBanking_transferFunds_Results_List{l}, err
}

func (s CoreBanking_transferFunds_Results_List) At(i int) CoreBanking_transferFunds_Results {
	return CoreBanking_transferFunds_Results{s.List.Struct(i)}
}

func (s CoreBanking_transferFunds_Results_List) Set(i int, v CoreBanking_transferFunds_Results) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s CoreBanking_transferFunds_Results_List) String() string {
	str, _ := text.MarshalList(0x951f644a900fb6e8, s.List)
	return str
}

// CoreBanking_transferFunds_Results_Promise is a wrapper for a CoreBanking_transferFunds_Results promised by a client call.
type CoreBanking_transferFunds_Results_Promise struct{ *capnp.Pipeline }

func (p CoreBanking_transferFunds_Results_Promise) Struct() (CoreBanking_transferFunds_Results, error) {
	s, err := p.Pipeline.Struct()
	return CoreBanking_transferFunds_Results{s}, err
}

func (p CoreBanking_transferFunds_Results_Promise) Res() Response_Promise {
	return Response_Promise{Pipeline: p.Pipeline.GetPipeline(0)}
}

type CoreBanking_getAccountInfo_Params struct{ capnp.Struct }

// CoreBanking_getAccountInfo_Params_TypeID is the unique identifier for the type CoreBanking_getAccountInfo_Params.
const CoreBanking_getAccountInfo_Params_TypeID = 0xc515f3fd4c51c8cd

func NewCoreBanking_getAccountInfo_Params(s *capnp.Segment) (CoreBanking_getAccountInfo_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return CoreBanking_getAccountInfo_Params{st}, err
}

func NewRootCoreBanking_getAccountInfo_Params(s *capnp.Segment) (CoreBanking_getAccountInfo_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return CoreBanking_getAccountInfo_Params{st}, err
}

func ReadRootCoreBanking_getAccountInfo_Params(msg *capnp.Message) (CoreBanking_getAccountInfo_Params, error) {
	root, err := msg.RootPtr()
	return CoreBanking_getAccountInfo_Params{root.Struct()}, err
}

func (s CoreBanking_getAccountInfo_Params) String() string {
	str, _ := text.Marshal(0xc515f3fd4c51c8cd, s.Struct)
	return str
}

func (s CoreBanking_getAccountInfo_Params) AccountId() ([]byte, error) {
	p, err := s.Struct.Ptr(0)
	return []byte(p.Data()), err
}

func (s CoreBanking_getAccountInfo_Params) HasAccountId() bool {
	p, err := s.Struct.Ptr(0)
	return p.IsValid() || err != nil
}

func (s CoreBanking_getAccountInfo_Params) SetAccountId(v []byte) error {
	return s.Struct.SetData(0, v)
}

// CoreBanking_getAccountInfo_Params_List is a list of CoreBanking_getAccountInfo_Params.
type CoreBanking_getAccountInfo_Params_List struct{ capnp.List }

// NewCoreBanking_getAccountInfo_Params creates a new list of CoreBanking_getAccountInfo_Params.
func NewCoreBanking_getAccountInfo_Params_List(s *capnp.Segment, sz int32) (CoreBanking_getAccountInfo_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return CoreBanking_getAccountInfo_Params_List{l}, err
}

func (s CoreBanking_getAccountInfo_Params_List) At(i int) CoreBanking_getAccountInfo_Params {
	return CoreBanking_getAccountInfo_Params{s.List.Struct(i)}
}

func (s CoreBanking_getAccountInfo_Params_List) Set(i int, v CoreBanking_getAccountInfo_Params) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s CoreBanking_getAccountInfo_Params_List) String() string {
	str, _ := text.MarshalList(0xc515f3fd4c51c8cd, s.List)
	return str
}

// CoreBanking_getAccountInfo_Params_Promise is a wrapper for a CoreBanking_getAccountInfo_Params promised by a client call.
type CoreBanking_getAccountInfo_Params_Promise struct{ *capnp.Pipeline }

func (p CoreBanking_getAccountInfo_Params_Promise) Struct() (CoreBanking_getAccountInfo_Params, error) {
	s, err := p.Pipeline.Struct()
	return CoreBanking_getAccountInfo_Params{s}, err
}

type CoreBanking_getAccountInfo_Results struct{ capnp.Struct }

// CoreBanking_getAccountInfo_Results_TypeID is the unique identifier for the type CoreBanking_getAccountInfo_Results.
const CoreBanking_getAccountInfo_Results_TypeID = 0xfc9887d1ffcbeba7

func NewCoreBanking_getAccountInfo_Results(s *capnp.Segment) (CoreBanking_getAccountInfo_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2})
	return CoreBanking_getAccountInfo_Results{st}, err
}

func NewRootCoreBanking_getAccountInfo_Results(s *capnp.Segment) (CoreBanking_getAccountInfo_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2})
	return CoreBanking_getAccountInfo_Results{st}, err
}

func ReadRootCoreBanking_getAccountInfo_Results(msg *capnp.Message) (CoreBanking_getAccountInfo_Results, error) {
	root, err := msg.RootPtr()
	return CoreBanking_getAccountInfo_Results{root.Struct()}, err
}

func (s CoreBanking_getAccountInfo_Results) String() string {
	str, _ := text.Marshal(0xfc9887d1ffcbeba7, s.Struct)
	return str
}

func (s CoreBanking_getAccountInfo_Results) Name() (string, error) {
	p, err := s.Struct.Ptr(0)
	return p.Text(), err
}

func (s CoreBanking_getAccountInfo_Results) HasName() bool {
	p, err := s.Struct.Ptr(0)
	return p.IsValid() || err != nil
}

func (s CoreBanking_getAccountInfo_Results) NameBytes() ([]byte, error) {
	p, err := s.Struct.Ptr(0)
	return p.TextBytes(), err
}

func (s CoreBanking_getAccountInfo_Results) SetName(v string) error {
	return s.Struct.SetText(0, v)
}

func (s CoreBanking_getAccountInfo_Results) Balance() uint64 {
	return s.Struct.Uint64(0)
}

func (s CoreBanking_getAccountInfo_Results) SetBalance(v uint64) {
	s.Struct.SetUint64(0, v)
}

func (s CoreBanking_getAccountInfo_Results) Res() (Response, error) {
	p, err := s.Struct.Ptr(1)
	return Response{Struct: p.Struct()}, err
}

func (s CoreBanking_getAccountInfo_Results) HasRes() bool {
	p, err := s.Struct.Ptr(1)
	return p.IsValid() || err != nil
}

func (s CoreBanking_getAccountInfo_Results) SetRes(v Response) error {
	return s.Struct.SetPtr(1, v.Struct.ToPtr())
}

// NewRes sets the res field to a newly
// allocated Response struct, preferring placement in s's segment.
func (s CoreBanking_getAccountInfo_Results) NewRes() (Response, error) {
	ss, err := NewResponse(s.Struct.Segment())
	if err != nil {
		return Response{}, err
	}
	err = s.Struct.SetPtr(1, ss.Struct.ToPtr())
	return ss, err
}

// CoreBanking_getAccountInfo_Results_List is a list of CoreBanking_getAccountInfo_Results.
type CoreBanking_getAccountInfo_Results_List struct{ capnp.List }

// NewCoreBanking_getAccountInfo_Results creates a new list of CoreBanking_getAccountInfo_Results.
func NewCoreBanking_getAccountInfo_Results_List(s *capnp.Segment, sz int32) (CoreBanking_getAccountInfo_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2}, sz)
	return CoreBanking_getAccountInfo_Results_List{l}, err
}

func (s CoreBanking_getAccountInfo_Results_List) At(i int) CoreBanking_getAccountInfo_Results {
	return CoreBanking_getAccountInfo_Results{s.List.Struct(i)}
}

func (s CoreBanking_getAccountInfo_Results_List) Set(i int, v CoreBanking_getAccountInfo_Results) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s CoreBanking_getAccountInfo_Results_List) String() string {
	str, _ := text.MarshalList(0xfc9887d1ffcbeba7, s.List)
	return str
}

// CoreBanking_getAccountInfo_Results_Promise is a wrapper for a CoreBanking_getAccountInfo_Results promised by a client call.
type CoreBanking_getAccountInfo_Results_Promise struct{ *capnp.Pipeline }

func (p CoreBanking_getAccountInfo_Results_Promise) Struct() (CoreBanking_getAccountInfo_Results, error) {
	s, err := p.Pipeline.Struct()
	return CoreBanking_getAccountInfo_Results{s}, err
}

func (p CoreBanking_getAccountInfo_Results_Promise) Res() Response_Promise {
	return Response_Promise{Pipeline: p.Pipeline.GetPipeline(1)}
}

const schema_aaa3acc39d94e0f8 = "x\xda\xb4\x93_h\x1cU\x18\xc5\xbfs\xef\xccN+" +
	"\x1b6\xe3F\xa8\x10X\xa9y\x88\x81\xb4\x0dQ\x90\"" +
	"\xecfk\xc4H\x02{\x93\x16|P\xe4f\xf6&\xae" +
	"\x9b\xbd\x13gf\x91\x14\xa5\xa0\xa0\xf8 X\xad\xa8H" +
	"A\x91\xe2\x1f\x8a\xa5R|\x10\x8bT\x11,\xe2\x83\xa0" +
	"\xa0o\x15\x04\xc5\xf5A*H\x11\xcb\xc8\xddufg" +
	"eQ\xb7\xe8\xdb2\xf7\xec9\xe7\xfb\xdd\xef\x1e\x98e" +
	"\x156g\xef\xb7\x89\xc4\x1dv.\xfe\xe1\xbd\xc2\xb3\xf7" +
	"\xd4K/\x90;\x0d\"\x1b\x0e\xd1\xfcc\xec2\x08\xc5" +
	"\xe3\xacL\x88\x17\xdf\xd9x\xee\xc9\x17\x1f\x7f\x8b\xdcI" +
	"\x1e_\xb9t\xe2\xe4\xc7\xa7_\x7f\x9b\x08\xf3gY\x15" +
	"\xc5\x0b\xcc\xfc\xe1<sPlq\x87(\xee\xacw:" +
	"\x1f]\xf7\xdd\xfbY\xbf#\xbc\xeb\xd7\xe0\xc6\xef\x99\xfc" +
	"}\xa7\xbf\x9e;\xf7\x01\xb9\x93\xd6\x80\xdf\xd3\xbc\x8a\xe2" +
	"\xcb\xc6d\xed\x04\xe7X{\x953\x10\xc5\x9f\x7f*\x96" +
	"\xaf\xfer\xc3'Y\xc3\xe3=\xc3S]\xc3w\xcf]" +
	"|\xf4\xc3\x07\x1e\xfa\x96\xc4$\xd0w\xec)/\xf2\x19" +
	"\x14\xbf1\xa6\xc5\xaf\xf8#\x84\xf8\xf0\x83\xd7\xeb\xf9\x1b" +
	"/|\x9f\xb5\x9b\xb3\xbav\x8b\x96\xb1{\xe2\xa7\xe7o" +
	"_y\xf3\x95\x9f\xb3\x02e\xfdh\x04;]A\xbe\xb9" +
	"\xe7\xfck\xa7.]&1\x0d\xa3\xe8\x128\xd9S\x9c" +
	"\xb5\xce\x10\xe2C\xd37_i~\xb9\xf3\xeb\x80b\xc5" +
	"\xee*\xa4m\x14ot>\x8b\xbfx\xea\xa5\xdf\x07\x14" +
	"W\xed\xdf\x8c\xc2\xcd\x9d\xa1\xd9\xd8\x0bv\xb6#\x7f]" +
	"\xe6ts\x7f\xf2[7\xf7yr[o\x1f<\xe4\x07" +
	"\xaa*u\xb3\xa17\xf7E\x81\xd4\xe1\x86\x0a\xeej\xeb" +
	"z8\xb5\xaaJa{+\x0a\x85\xc5-\"\x0bD\xee" +
	"\xd8^\"\xb1\x8bCL08\x81\x0a1\xdeGF\xc0" +
	"8!\x0d\xb3\xfe!\x8cj\x80\x18\xe76Q:#\x92" +
	"\x0bw\x1f\x0e\x88\xb9\x0d\x07}\x84H`\xbb\xf7\x9b\xb3" +
	"#\x0eXJ\x0f\xc9\xe2\xb9K\xe6l\xc1\x01O\xaf\x1a" +
	"\x09\x1e\xf7\xb6\xa3\xc4\xdcY'\xf6\x02%#\xb5\xe0Q" +
	"\xc9\xf3\xdb:\xaa \xae\xab-5\xf8%\x01A\xa5." +
	"\x8a\x0a\xe2M\x15-x\x9e\xdf\xa6\xb2\x8e\x96\xf4\x86_" +
	"A\x0d\xf8\xf7d\x93\xd0n\xc0\xffAV\xf6\xac\xd7\x1a" +
	"G\x95!\x8b\x1c1;w\x13\x8dP1\x99\xb07\xdf" +
	"T\xad$\x03\xd9\x1a\xa8\xb8J$\xf2\x1cb\x0fC\xfc" +
	"g\xde\x12\xa1\x8e1b\x18\xcbD\xf1aQ\xab*\xdc" +
	".\xf8:T\xe6\xdew\xa5\xa6\xb7\xcc\x10\x89)\x0eq" +
	"\x80\x01\x980\x1b\xec\xceV\x89\xc44\x87\xb8\x95\xa1\xe0" +
	"\xf9u\x05\x8b\x18,\xc2\xb1\x96\x0aC\xb9\xa9\x90'\x86" +
	"\xfc(\xc3%W\xfc_\xf0\x1f1\xac&\x0b\xd7\x0ar" +
	"\xc4\x07\x9b$\xe5\xd3\xa4\xc5\x83D\xa2\xc2!\x96\x19\xdc" +
	"\x04\xef\xd2:\x91\xb8\x9bC\x1cf\x00\x9b\x00#r\x85" +
	"\x11.s\x88{\x19\xca\xa1\xdf\x0e<\x95\xb6\xa9\xab0" +
	"jh\x19\x91\xd3\xf0u\xf2\xb5,[\xa66v\x13\xc3" +
	"n\xba\xe6\x970\xa4\xb2\x81s'\x87\xa8e*\xaf\xcc" +
	"\x0c\xa9\\\xedW\x1eF\xb1\xa0e+\xdd\x94c\xebr" +
	"KjO\x8d\xde\xf7/\xcfb\xb5\xacz\xab\x93i<" +
	"\xd3\x87\x9c2\xaef\xa6`\xe85^\xd9\xdb\x9f\xe2o" +
	"\xdb\x0d_\xc0?\x02\x00\x00\xff\xffb\xcd\x1eW"

func init() {
	schemas.Register(schema_aaa3acc39d94e0f8,
		0x951f644a900fb6e8,
		0xa98297869266ae45,
		0xbae40ac2ebeb62eb,
		0xbcb431d8ac5c0c8d,
		0xc515f3fd4c51c8cd,
		0xe16a5fbf7cc9b4b2,
		0xe7c119336e126854,
		0xf09ba84d3893ec83,
		0xf2e0a5a1bd186b0c,
		0xf679d46bf8232843,
		0xfc9887d1ffcbeba7)
}
